site_name: AISS
nav:
    - Home: Readme.md
    - About: about.md
    - Guide: guide.md
    - How to install docker: install_docker.md
    - How to install docker compose: install_docker_compose.md

theme: readthedocs